# Site settings
title: "Genomics Privacy-Perserving Federated Learning at NIST"
description: "Documentation for Privacy-Perserving Federated Learning red teaming exercises at NIST."

baseurl: "/genomics_ppfl"  
rooturl: ""
